version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=dana
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  broker:
    image: emqx/emqx:latest
    ports: 
      - "18083:18083"
      - "1883:1883"
      - "8083:8083"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - PMA_HOST=db
    ports:
      - '8080:80'
    depends_on:
      - db 



